### ISSUE TITLE
i got this error with ngrok

### ISSUE THREAD

**Issue by mohqwt0** [wandaweb/Fooocus-Sagemaker-Studio-Lab#1]
ERR_NGROK_8012
Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at [localhost:7860](http://localhost:7860/). The error encountered was:

dial tcp 127.0.0.1:7860: connect: connection refused
[Get help with this error](https://ngrok.com/docs/errors/err_ngrok_8012)

App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
t=2023-11-15T20:08:47+0000 lvl=warn msg="failed to open private leg" id=0024f6e22e01 privaddr=localhost:7861 err="dial tcp 127.0.0.1:7861: connect: connection refused"
^CKeyboard interruption in main thread... closing server.
You pressed Ctrl+C!

**Comment by wandaweb** [comment]
Thanks for opening the issue! Fooocus changed their default port from 7860 to 7865. I updated the port in start-ngrok.py, so it should work now if you pull the latest changes.
