### ISSUE TITLE
I am facing issue on libgthread 

### ISSUE THREAD

**Issue by sibisanjai2001** [wandaweb/Fooocus-Sagemaker-Studio-Lab#11]
This is the error i am getting,

Press Ctrl+C to exit
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus/entry_with_update.py', '--always-high-vram']
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Fooocus version: 2.3.0
Version mismatch for Pillow: Installed version 10.2.0 does not meet requirement Pillow==9.2.0
Installing requirements
Traceback (most recent call last):
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/launch.py", line 83, in <module>
    from modules import config
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/config.py", line 8, in <module>
    import modules.sdxl_styles
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/sdxl_styles.py", line 7, in <module>
    from modules.util import get_files_from_folder
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/util.py", line 8, in <module>
    import cv2
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

![image](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/109585353/145f43c9-1f99-4ccf-8ae9-1878795b4bbd)

**Comment by wandaweb** [comment]
Hi, please try using the updated model-management notebook to delete the existing installation by running the last code block and then reinstall Foocus by running start.sh

I fixed an issue where conda was failing to install glib, so a fresh install using the new script should work.

**Comment by sibisanjai2001** [comment]
> Hi, please try using the updated model-management notebook to delete the existing installation by running the last code block and then reinstall Foocus by running start.sh
> 
> I fixed an issue where conda was failing to install glib, so a fresh install using the new script should work.

Again facing the same issue i reinstalled the model also i am getting the same kind of error 

![image](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/109585353/6fdd9e4d-0a62-496c-ae1b-e88885372a5f)

**Comment by wandaweb** [comment]
In line 4 of your output, it says "Could not find conda environment: fooocus", which means the fooocus conda environment doesn't exist. This is what's causing the error. 

I was not able to reproduce this on a clean install, so I'm not sure what happened on your instance that caused it. I suggest clearing out the /tmp folder and deleting ~/.conda/envs/fooocus if it exists, downloading the latest start.sh script and trying again with a clean install.

**Comment by sibisanjai2001** [comment]
I created the another account using different E mail id that instance was working fine fine no issue. only facing the issue to the particular account getting an "error'' i clear the temp file also but  again getting same error how to fully reset the account any idea!    ?

**Comment by wandaweb** [comment]
A quick way to delete all data and conda environments is to open a terminal and run:
`rm -rf ~/*`
`rm -rf ~/.conda/envs/*`
Restarting the instance will re-create the default and studiolab conda environments. What I usually do is just delete conda envrionments I don't need from the file browser, so I don't need to restart my runtime.

**Comment by sibisanjai2001** [comment]
rm -rf ~/*
rm -rf ~/.conda/envs/*

 This command working fine issue resolved. once clear the conda environment  👌
