### ISSUE TITLE
Juggernaut systematic installation

### ISSUE THREAD

**Issue by VigoZy** [wandaweb/Fooocus-Sagemaker-Studio-Lab#12]
Thank you for this improvement, and for installing Fooocus reduced to its essentials. But I have a problem, I follow your recommendation regarding changing the default model in the ctrl.txt file and I continue to have juggernaut which installs systematically. What to do ? I know that some civitai models are private and require authorization, I solved this problem by changing what was necessary in the "model_management.ipynb" file. It works now. Is it for the same reason that Juggernaut systematically imposes itself?

**Comment by wandaweb** [comment]
I added a sample config file that replaces the Juggernaut model with IrisLux. You can change it to an arbitrary model. I tested it today after deleting Juggernaut from the models folder and it didn't download anything except IrisLux if it wasn't already there.

**Comment by VigoZy** [comment]
Ok thx very much, I try !!!

**Comment by VigoZy** [comment]
It works perfectly, no doubt I had forgotten a comma or something I don't know what. Sorry, and thank you again

**Comment by wandaweb** [comment]
I'm glad it worked! I'll close the issue 😊
