### ISSUE TITLE
can't load lora after refresh all files

### ISSUE THREAD

**Issue by mochtarluthfieffendy** [wandaweb/Fooocus-Sagemaker-Studio-Lab#13]
hallo, thank for updated. all code running smoothly, but afte downloaded lora from civitai, its cant load after i press refresh all files.

**Comment by wandaweb** [comment]
Check the LoRA is in the right folder by navigating to the Fooocus/models/loras folder in Sagemaker's file browser on the left hand side.

Another thing you can try is running the first code block in the file management notebook, to re-initialize variables. In the output, you can check if it got the right folder, and if it prints out an error, try restarting the kernel by going to Kernel -> Restart Kernel in the top menu.

**Comment by mochtarluthfieffendy** [comment]
I've tried. In the file manager, Lora has been successfully installed, but in Fooocus it is not detected. either permanent or temporary.
