### ISSUE TITLE
Can't open Checkpoint Folder

### ISSUE THREAD

**Issue by Yui007** [wandaweb/Fooocus-Sagemaker-Studio-Lab#2]
hi thanks for the notebook but there is one single issue no matter how much i tried i cant open the checkpoint folder in the notebook because i want to delete the checkpoint and download new ones but i cant open it. there is also one other guy who asked you the same question on youtube

**Comment by wandaweb** [comment]
Thanks for opening the issue. You're right - Sagemaker's file manager won't open a folder called "checkpoints". I updated the script to change the folder name to checkpoints-real-folder, which works in the file manager, so you can navigate to it, and add or delete files.

To apply the change, please replace your "start.sh" with the updated file and run it again. 😊

**Comment by Yui007** [comment]
Thank you so much for replying me and fixing it so fast😊😊😊
