### ISSUE TITLE
Fooocus stopped because of the High uses of ram and gpu ram is not utilizing properly

### ISSUE THREAD

**Issue by AlanTuring42** [wandaweb/Fooocus-Sagemaker-Studio-Lab#3]
Hey for heavy workload my Fooocus  process crashed multiple time on SageMaker. When I checked I saw that the RAM usage consistently approached its limit. I've faced the similar issue on Colab. Can you just implement this line on your code to utilize the free vram in the mix.

`!python entry_with_update.py --share --always-high-vram`

### When I didn't specify on colab, simple workload, (can't to heavy workload cause the ram exceeded the limit and it crashes)
 <img width="416" alt="Screen Shot 2023-12-14 at 4 56 33 PM" src="https://github.com/lllyasviel/Fooocus/assets/52377889/f27ac4bf-e031-4876-a212-673390696f8a">

### When I specify vram on colab, heavy workload with big checkpoints
<img width="139" alt="Screen Shot 2023-12-17 at 7 27 21 PM" src="https://github.com/lllyasviel/Fooocus/assets/52377889/5ae2b1d9-1bd4-4003-8d1a-5a9a122152e4">

### When I didn't specify on sagemaker, simple workload, (can't to heavy workload cause the ram exceeded the limit and it crashes)
<img width="615" alt="Screen Shot 2023-12-18 at 1 42 46 PM" src="https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/52377889/ffa64557-397c-4079-bdd4-a58fb28ba728">
<img width="607" alt="Screen Shot 2023-12-18 at 1 42 28 PM" src="https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/52377889/17c29f51-72f0-4b1f-af63-9fa9846eaf2c">

### When I did specify the high vram on sagemaker, heavy workload with big checkpoints
<img width="643" alt="Screen Shot 2023-12-18 at 1 36 27 PM" src="https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/52377889/d3f26a89-e028-408c-ac55-07b2450a6d49">
<img width="716" alt="Screen Shot 2023-12-18 at 1 36 04 PM" src="https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/52377889/156e19b7-28c4-40e7-9c23-571c841c2e66">

Details: https://github.com/lllyasviel/Fooocus/issues/1377

**Comment by Deepch7890** [comment]
Still having same issue , anyone find the solution (I'm new to this)
![image](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/157013700/4906b74d-8c94-42c7-8502-2de7fb35d9eb)
![image](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/157013700/2e102a00-42b0-4d6e-880d-bee6e3b56f94)

**Comment by Deepch7890** [comment]
![image](https://github.com/wandaweb/Fooocus-Sagemaker-Studio-Lab/assets/157013700/445f6b40-c29c-4f25-b91f-23e8b485bdb3)
